"""Single source for effective pipeline defaults recorded in canonical run metadata."""

# Read-pair QC
MIN_READ_LENGTH = 130
MIN_MEAN_PHRED = 25
BARCODE_LENGTH = 20
MIN_BARCODE_Q25 = 15

# Primer classification
PRIMER_MAX_SHIFT = 4
PRIMER_MAX_MISMATCHES = 4
R2_PRIMER_START = 42
VALID_16S_R1_STARTS = tuple(range(10))

# Barcode clustering and taxonomy filtering
BARCODE_MAX_SHIFT = 1
MIN_16S_READS = 5
MAX_TAXONOMY_CONTAMINATION = 0.1
DEFAULT_MIN_CELLS_PER_TAXON = 10

# Taxonomy MLE
MLE_P_MATCH = 0.90
MLE_P_NONE = 0.09
MLE_P_ERROR = 0.01
MLE_ALPHA_PRIOR = 1.0
MLE_BETA_PRIOR = 9.0
MLE_MIN_CONFIDENCE = 0.95
MLE_MIN_NOISE_READS = 2
MLE_NOISE_CUTOFF_RATIO = 0.05

# ASV analysis
ASV_MAX_DISTANCE = 3
ASV_MAX_SHIFT = 3
ASV_MIN_READS = 5
ASV_MIXED_RATIO_THRESHOLD = 0.10
ASV_R1_START = 30
ASV_R1_END = 120
ASV_R2_START = 70
ASV_R2_END = 120
ASV_TAXONOMY_CONFLICT_MIN_CELLS = 10
ASV_TAXONOMY_CONFLICT_DOMINANCE = 0.99
# 2026-09-21: Define final ASV support independently of dataset size.
# Reason: final reporting should exclude both rare absolute and rare relative ASVs.
ASV_FINAL_MIN_CELL_FRACTION = 0.005
ASV_FINAL_MIN_CELL_COUNT = 10

# Target background filtering and reconstructed target sequences
TARGET_BACKGROUND_ALPHA = 0.05
TARGET_SEQUENCE_ALPHA = 0.05
TARGET_SEQUENCE_MAX_SHIFT = 2
TARGET_SEQUENCE_MAX_MISMATCHES = 0
TARGET_R1_START = 30
TARGET_R1_END = 120
TARGET_R2_START = 70
TARGET_R2_END = 120
